# notifications-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gnx-apps-ns
  name: notifications
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: notifications # Select pods with this label
  template:
    metadata:
      labels:
        app: notifications # Label for the pods
    spec:
      containers:
        - name: notifications-container
          image: genocs/notifications-webapi:1.0.4 # Replace with your image
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: logger__level
              value: "Debug"

            # RabbitMQ
            - name: rabbitmq__hostname
              value: "flamingo.rmq.cloudamqp.com"
            - name: rabbitmq__hostnames__0
              value: "flamingo.rmq.cloudamqp.com"
            - name: rabbitmq__virtualhost
              value: "zcoqmbte"
            - name: rabbitmq__username
              valueFrom:
                secretKeyRef:
                  name: gnx-app-secrets
                  key: RABBITMQ_USER_NAME
            - name: rabbitmq__password
              valueFrom:
                secretKeyRef:
                  name: gnx-app-secrets
                  key: RABBITMQ_PASSWORD
            # MongoDB
            - name: mongodb__connectionString
              valueFrom:
                secretKeyRef:
                  name: gnx-app-secrets
                  key: MONGODB_CONNECTION_STRING

          ports:
            - containerPort: 8080 # Port the container exposes
          resources: # Optional resource requests and limits
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
