services:
  application.webapi:
    image: genocs/demo-webapi:2.0.0
    build:
      context: ../
      dockerfile: ../src/demo/Genocs.Core.Demo.WebApi/Dockerfile

  application.worker:
    image: genocs/demo-worker:2.0.0
    build:
      context: ../
      dockerfile: ../src/demo/Genocs.Core.Demo.Worker/Dockerfile
