apiVersion: v1
kind: Secret
metadata:
  name: gnx-app-secrets
  namespace: gnx-apps

type: Opaque
data:
  MONGODB_CONNECTION_STRING: mongodb://mongodb:27017
  RABBITMQ_HOST_NAME: rabbitmq
  RABBITMQ_VIRTUAL_HOST: /
  RABBITMQ_USER_NAME: guest
  RABBITMQ_PASSWORD: guest
