services:
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    hostname: aspire_dashboard
    container_name: aspire_dashboard
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    networks:
      - genocs

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - genocs
    # network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana

  influxdb:
    image: influxdb
    hostname: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    networks:
      - genocs
    # network_mode: host
    volumes:
      - influxdb_data:/var/lib/influxdb2

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    container_name: jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - genocs

  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - genocs
    volumes:
      - prometheus_data:/etc/prometheus

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 5341:5341 # ingestion
      - 5380:80 # UI
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    networks:
      - genocs
    # network_mode: host
    volumes:
      - seq_data:/data

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  prometheus_data:
    driver: local
  seq_data:
    driver: local
